### ISSUE TITLE
VCV Rack 2

### ISSUE THREAD

**Issue by pgatt** [alikins/Alikins-rack-plugins#19]
Hi there, I use your modules all the time in Rack, just wondering if you will be updating them to VCV Rack 2?

Thanks,
Paul.

**Comment by netboy3** [comment]
I've just completed migrating the plugin to V2 and fixing a few bugs. I've posted a PR #20 for your review and merge. I'm attaching below pre-built test binaries of the plugin for all three platforms. Please make sure to open the zip file below and pick the plugin binary for your platform. The binaries were built from modified sources [posted to my repository](https://github.com/netboy3/Alikins-vcvrack-plugins/tree/v2) and built as of commit 3ee48b0

[Alikins-2.0.1.zip](https://github.com/alikins/Alikins-rack-plugins/files/7781150/Alikins-2.0.1.zip)

**Comment by alikins** [comment]
@netboy3's patch has been merged and module is available in the library for v2 now.
