### ISSUE TITLE
Alikins' Specific Values Bug in Octave Selector

### ISSUE THREAD

**Issue by buckydurddle** [alikins/Alikins-rack-plugins#3]
Bug found in the Octave selector of the Specific Values module.

<center>![specific value.jpeg](https://cdn.utopian.io/posts/a1c9e56f4a6ba0e7e0e33b18561df610f332specific_value.jpeg)
</center>

#### Expected behavior
The octave selector in Specific Values should alter the frequency of the displays and the output control voltage. It should incrementally increase and decrease the frequencies by 1-octave steps.
<center>![in out.jpeg](https://cdn.utopian.io/posts/df07f4a03efa166807ced5d59b9ff7d9f8f3in_out.jpeg)
</center>

#### Actual behavior
The octave selector does change the values shown in the displays appropriately, but does not change the output control voltage (audio). The audio signal remains the same as before a selection was made with the octave selector.

#### How to reproduce
The bug can easily be reproduced by trying to use the function normally. Rotate the octave dial and no changes occur in the control voltage output (audio). 

Operating System:

![os.jpeg](https://cdn.utopian.io/posts/79fa08af58d4448be5898e77cbc1f7365853os.jpeg)

VCV Rack version 0.6.0

#### Recording Of The Bug
<iframe width="560" height="315" src="https://www.youtube.com/embed/0kJjMcEhwWQ?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@buckydurddle/alikins-specific-values-bug-in-octave-selector">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by alikins** [comment]
> The octave selector does change the values shown in the displays appropriately, but does not change the output control voltage (audio). The audio signal remains the same as before a selection was made with the octave selector.

That is more or less the intended behavior, I think. The octave control is supposed to change what frequency 0V corresponds to (defaulting to C4 261.626 Hz based on https://vcvrack.com/manual/VoltageStandards.html). 

So changing the octave value doesn't change the voltage output, but does change it's baseline reference value. Intended use is to adjust the displayed freq/note when used to control oscillator modules that don't use the 0V=C4 standard (the Befaco EvenVCO for example)

**Comment by alikins** [comment]
Old bug I forgot to follow up on. Sorry.

I removed the octave switch in later versions, since it was added just for compatibility with some of the early VCO's that were standard (the previously mentioned EvenVCO for ex)
